# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:SymfonyUser
                property: email
        memory_provider:
            memory:
                users:
                    sensei:
                        password: $2y$12$urJLEiqdh8sXIOZR0q.tFuUZXEhIN//Ac7wwDrHeK7xW6T2W2jz3G
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\SymfonyUser:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_content:
            pattern: ^/admin
            http_basic:
                provider: memory_provider

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            provider: our_db_provider

            form_login:
                login_path: /index
                check_path: /index/auth/login
                default_target_path: /index/hold
            logout:
                path: /logout
                target: /index

    role_hierarchy:
        ROLE_ADMIN: ROLE_NORMALUSER
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
